export const COUNTRY_CODES = [
  "zimbabwe",
  "zambia",
  "yemen",
  "us-virgin-islands",
  "vietnam",
  "venezuela",
  "vanuatu",
  "uzbekistan",
  "uruguay",
  "united-states",
  "united-kingdom",
  "united-arab-emirates",
  "ukraine",
  "uganda",
  "tuvalu",
  "turkmenistan",
  "turkey",
  "tunisia",
  "trinidad-and-tobago",
  "tonga",
  "togo",
  "timor-leste",
  "thailand",
  "tanzania",
  "tajikistan",
  "syria",
  "switzerland",
  "sweden",
  "suriname",
  "sudan",
  "sri-lanka",
  "spain",
  "south-sudan",
  "south-korea",
  "south-africa",
  "somalia",
  "solomon-islands",
  "slovenia",
  "slovakia",
  "sint-maarten",
  "singapore",
  "sierra-leone",
  "seychelles",
  "serbia",
  "senegal",
  "saudi-arabia",
  "sao-tome-and-principe",
  "san-marino",
  "samoa",
  "saint-vincent-and-the-grenadines",
  "saint-lucia",
  "rwanda",
  "russia",
  "romania",
  "qatar",
  "portugal",
  "poland",
  "philippines",
  "peru",
  "paraguay",
  "papua-new-guinea",
  "panama",
  "palestine",
  "palau",
  "pakistan",
  "oman",
  "norway",
  "north-macedonia",
  "nigeria",
  "niger",
  "nicaragua",
  "new-zealand",
  "netherlands",
  "nepal",
  "nauru",
  "namibia",
  "myanmar",
  "mozambique",
  "morocco",
  "montenegro",
  "mongolia",
  "monaco",
  "moldova",
  "micronesia",
  "mexico",
  "mauritius",
  "mauritania",
  "marshall-islands",
  "malta",
  "mali",
  "maldives",
  "malaysia",
  "malawi",
  "madagascar",
  "luxembourg",
  "lithuania",
  "liechtenstein",
  "libya",
  "liberia",
  "lesotho",
  "lebanon",
  "latvia",
  "laos",
  "kyrgyzstan",
  "kuwait",
  "kiribati",
  "kenya",
  "kazakhstan",
  "jordan",
  "japan",
  "jamaica",
  "ivory-coast",
  "italy",
  "israel",
  "ireland",
  "iraq",
  "iran",
  "indonesia",
  "india",
  "iceland",
  "hungary",
  "hong-kong",
  "honduras",
  "vatican-city",
  "haiti",
  "guyana",
  "guinea-bissau",
  "guinea",
  "guatemala",
  "grenada",
  "greece",
  "ghana",
  "germany",
  "georgia",
  "gambia",
  "gabon",
  "france",
  "finland",
  "fiji",
  "ethiopia",
  "eswatini",
  "estonia",
  "eritrea",
  "equatorial-guinea",
  "el-salvador",
  "egypt",
  "ecuador",
  "dominican-republic",
  "dominica",
  "djibouti",
  "denmark",
  "democratic-republic-of-the-congo",
  "czechia",
  "cyprus",
  "curacao",
  "cuba",
  "croatia",
  "costa-rica",
  "republic-of-the-congo",
  "comoros",
  "colombia",
  "china",
  "chile",
  "chad",
  "central-african-republic",
  "cape-verde",
  "canada",
  "cameroon",
  "cambodia",
  "burundi",
  "burkina-faso",
  "bulgaria",
  "brunei",
  "brazil",
  "bouvet-island",
  "botswana",
  "bosnia-and-herzegovina",
  "bolivia",
  "bhutan",
  "benin",
  "belize",
  "belgium",
  "belarus",
  "barbados",
  "bangladesh",
  "bahrain",
  "bahamas",
  "azerbaijan",
  "austria",
  "aruba",
  "armenia",
  "argentina",
  "australia",
  "antigua-and-barbuda",
  "angola",
  "andorra",
  "algeria",
  "albania",
  "afghanistan",
] as const

export type CountryCode = (typeof COUNTRY_CODES)[number]

export interface Country {
  code: CountryCode
  flag: string
}

export const COUNTRIES: Country[] = [
  { code: "zimbabwe", flag: "/icons/flag/flag-0.svg" },
  { code: "zambia", flag: "/icons/flag/flag-1.svg" },
  { code: "yemen", flag: "/icons/flag/flag-2.svg" },
  { code: "us-virgin-islands", flag: "/icons/flag/flag-3.svg" },
  { code: "vietnam", flag: "/icons/flag/flag-4.svg" },
  { code: "venezuela", flag: "/icons/flag/flag-5.svg" },
  { code: "vanuatu", flag: "/icons/flag/flag-6.svg" },
  { code: "uzbekistan", flag: "/icons/flag/flag-7.svg" },
  { code: "uruguay", flag: "/icons/flag/flag-8.svg" },
  { code: "united-states", flag: "/icons/flag/flag-9.svg" },
  { code: "united-kingdom", flag: "/icons/flag/flag-10.svg" },
  { code: "united-arab-emirates", flag: "/icons/flag/flag-11.svg" },
  { code: "ukraine", flag: "/icons/flag/flag-12.svg" },
  { code: "uganda", flag: "/icons/flag/flag-13.svg" },
  { code: "tuvalu", flag: "/icons/flag/flag-14.svg" },
  { code: "turkmenistan", flag: "/icons/flag/flag-15.svg" },
  { code: "turkey", flag: "/icons/flag/flag-16.svg" },
  { code: "tunisia", flag: "/icons/flag/flag-17.svg" },
  { code: "trinidad-and-tobago", flag: "/icons/flag/flag-18.svg" },
  { code: "tonga", flag: "/icons/flag/flag-19.svg" },
  { code: "togo", flag: "/icons/flag/flag-20.svg" },
  { code: "timor-leste", flag: "/icons/flag/flag-21.svg" },
  { code: "thailand", flag: "/icons/flag/flag-22.svg" },
  { code: "tanzania", flag: "/icons/flag/flag-23.svg" },
  { code: "tajikistan", flag: "/icons/flag/flag-24.svg" },
  { code: "syria", flag: "/icons/flag/flag-25.svg" },
  { code: "switzerland", flag: "/icons/flag/flag-26.svg" },
  { code: "sweden", flag: "/icons/flag/flag-27.svg" },
  { code: "suriname", flag: "/icons/flag/flag-28.svg" },
  { code: "sudan", flag: "/icons/flag/flag-29.svg" },
  { code: "sri-lanka", flag: "/icons/flag/flag-30.svg" },
  { code: "spain", flag: "/icons/flag/flag-31.svg" },
  { code: "south-sudan", flag: "/icons/flag/flag-32.svg" },
  { code: "south-korea", flag: "/icons/flag/flag-33.svg" },
  { code: "south-africa", flag: "/icons/flag/flag-34.svg" },
  { code: "somalia", flag: "/icons/flag/flag-35.svg" },
  { code: "solomon-islands", flag: "/icons/flag/flag-36.svg" },
  { code: "slovenia", flag: "/icons/flag/flag-37.svg" },
  { code: "slovakia", flag: "/icons/flag/flag-38.svg" },
  { code: "sint-maarten", flag: "/icons/flag/flag-39.svg" },
  { code: "singapore", flag: "/icons/flag/flag-40.svg" },
  { code: "sierra-leone", flag: "/icons/flag/flag-41.svg" },
  { code: "seychelles", flag: "/icons/flag/flag-42.svg" },
  { code: "serbia", flag: "/icons/flag/flag-43.svg" },
  { code: "senegal", flag: "/icons/flag/flag-44.svg" },
  { code: "saudi-arabia", flag: "/icons/flag/flag-45.svg" },
  { code: "sao-tome-and-principe", flag: "/icons/flag/flag-46.svg" },
  { code: "san-marino", flag: "/icons/flag/flag-47.svg" },
  { code: "samoa", flag: "/icons/flag/flag-48.svg" },
  { code: "saint-vincent-and-the-grenadines", flag: "/icons/flag/flag-49.svg" },
  { code: "saint-lucia", flag: "/icons/flag/flag-50.svg" },
  { code: "rwanda", flag: "/icons/flag/flag-51.svg" },
  { code: "russia", flag: "/icons/flag/flag-52.svg" },
  { code: "romania", flag: "/icons/flag/flag-53.svg" },
  { code: "qatar", flag: "/icons/flag/flag-54.svg" },
  { code: "portugal", flag: "/icons/flag/flag-55.svg" },
  { code: "poland", flag: "/icons/flag/flag-56.svg" },
  { code: "philippines", flag: "/icons/flag/flag-57.svg" },
  { code: "peru", flag: "/icons/flag/flag-58.svg" },
  { code: "paraguay", flag: "/icons/flag/flag-59.svg" },
  { code: "papua-new-guinea", flag: "/icons/flag/flag-60.svg" },
  { code: "panama", flag: "/icons/flag/flag-61.svg" },
  { code: "palestine", flag: "/icons/flag/flag-62.svg" },
  { code: "palau", flag: "/icons/flag/flag-63.svg" },
  { code: "pakistan", flag: "/icons/flag/flag-64.svg" },
  { code: "oman", flag: "/icons/flag/flag-65.svg" },
  { code: "norway", flag: "/icons/flag/flag-66.svg" },
  { code: "north-macedonia", flag: "/icons/flag/flag-67.svg" },
  { code: "nigeria", flag: "/icons/flag/flag-68.svg" },
  { code: "niger", flag: "/icons/flag/flag-69.svg" },
  { code: "nicaragua", flag: "/icons/flag/flag-70.svg" },
  { code: "new-zealand", flag: "/icons/flag/flag-71.svg" },
  { code: "netherlands", flag: "/icons/flag/flag-72.svg" },
  { code: "nepal", flag: "/icons/flag/flag-73.svg" },
  { code: "nauru", flag: "/icons/flag/flag-74.svg" },
  { code: "namibia", flag: "/icons/flag/flag-75.svg" },
  { code: "myanmar", flag: "/icons/flag/flag-76.svg" },
  { code: "mozambique", flag: "/icons/flag/flag-77.svg" },
  { code: "morocco", flag: "/icons/flag/flag-78.svg" },
  { code: "montenegro", flag: "/icons/flag/flag-79.svg" },
  { code: "mongolia", flag: "/icons/flag/flag-80.svg" },
  { code: "monaco", flag: "/icons/flag/flag-81.svg" },
  { code: "moldova", flag: "/icons/flag/flag-82.svg" },
  { code: "micronesia", flag: "/icons/flag/flag-83.svg" },
  { code: "mexico", flag: "/icons/flag/flag-84.svg" },
  { code: "mauritius", flag: "/icons/flag/flag-85.svg" },
  { code: "mauritania", flag: "/icons/flag/flag-86.svg" },
  { code: "marshall-islands", flag: "/icons/flag/flag-87.svg" },
  { code: "malta", flag: "/icons/flag/flag-88.svg" },
  { code: "mali", flag: "/icons/flag/flag-89.svg" },
  { code: "maldives", flag: "/icons/flag/flag-90.svg" },
  { code: "malaysia", flag: "/icons/flag/flag-91.svg" },
  { code: "malawi", flag: "/icons/flag/flag-92.svg" },
  { code: "madagascar", flag: "/icons/flag/flag-93.svg" },
  { code: "luxembourg", flag: "/icons/flag/flag-94.svg" },
  { code: "lithuania", flag: "/icons/flag/flag-95.svg" },
  { code: "liechtenstein", flag: "/icons/flag/flag-96.svg" },
  { code: "libya", flag: "/icons/flag/flag-97.svg" },
  { code: "liberia", flag: "/icons/flag/flag-98.svg" },
  { code: "lesotho", flag: "/icons/flag/flag-99.svg" },
  { code: "lebanon", flag: "/icons/flag/flag-100.svg" },
  { code: "latvia", flag: "/icons/flag/flag-101.svg" },
  { code: "laos", flag: "/icons/flag/flag-102.svg" },
  { code: "kyrgyzstan", flag: "/icons/flag/flag-103.svg" },
  { code: "kuwait", flag: "/icons/flag/flag-104.svg" },
  { code: "kiribati", flag: "/icons/flag/flag-105.svg" },
  { code: "kenya", flag: "/icons/flag/flag-106.svg" },
  { code: "kazakhstan", flag: "/icons/flag/flag-107.svg" },
  { code: "jordan", flag: "/icons/flag/flag-108.svg" },
  { code: "japan", flag: "/icons/flag/flag-109.svg" },
  { code: "jamaica", flag: "/icons/flag/flag-110.svg" },
  { code: "ivory-coast", flag: "/icons/flag/flag-111.svg" },
  { code: "italy", flag: "/icons/flag/flag-112.svg" },
  { code: "israel", flag: "/icons/flag/flag-113.svg" },
  { code: "ireland", flag: "/icons/flag/flag-114.svg" },
  { code: "iraq", flag: "/icons/flag/flag-115.svg" },
  { code: "iran", flag: "/icons/flag/flag-116.svg" },
  { code: "indonesia", flag: "/icons/flag/flag-117.svg" },
  { code: "india", flag: "/icons/flag/flag-118.svg" },
  { code: "iceland", flag: "/icons/flag/flag-119.svg" },
  { code: "hungary", flag: "/icons/flag/flag-120.svg" },
  { code: "hong-kong", flag: "/icons/flag/flag-121.svg" },
  { code: "honduras", flag: "/icons/flag/flag-122.svg" },
  { code: "vatican-city", flag: "/icons/flag/flag-123.svg" },
  { code: "haiti", flag: "/icons/flag/flag-124.svg" },
  { code: "guyana", flag: "/icons/flag/flag-125.svg" },
  { code: "guinea-bissau", flag: "/icons/flag/flag-126.svg" },
  { code: "guinea", flag: "/icons/flag/flag-127.svg" },
  { code: "guatemala", flag: "/icons/flag/flag-128.svg" },
  { code: "grenada", flag: "/icons/flag/flag-129.svg" },
  { code: "greece", flag: "/icons/flag/flag-130.svg" },
  { code: "ghana", flag: "/icons/flag/flag-131.svg" },
  { code: "germany", flag: "/icons/flag/flag-132.svg" },
  { code: "georgia", flag: "/icons/flag/flag-133.svg" },
  { code: "gambia", flag: "/icons/flag/flag-134.svg" },
  { code: "gabon", flag: "/icons/flag/flag-135.svg" },
  { code: "france", flag: "/icons/flag/flag-136.svg" },
  { code: "finland", flag: "/icons/flag/flag-137.svg" },
  { code: "fiji", flag: "/icons/flag/flag-138.svg" },
  { code: "ethiopia", flag: "/icons/flag/flag-139.svg" },
  { code: "eswatini", flag: "/icons/flag/flag-140.svg" },
  { code: "estonia", flag: "/icons/flag/flag-141.svg" },
  { code: "eritrea", flag: "/icons/flag/flag-142.svg" },
  { code: "equatorial-guinea", flag: "/icons/flag/flag-143.svg" },
  { code: "el-salvador", flag: "/icons/flag/flag-144.svg" },
  { code: "egypt", flag: "/icons/flag/flag-145.svg" },
  { code: "ecuador", flag: "/icons/flag/flag-146.svg" },
  { code: "dominican-republic", flag: "/icons/flag/flag-147.svg" },
  { code: "dominica", flag: "/icons/flag/flag-148.svg" },
  { code: "djibouti", flag: "/icons/flag/flag-149.svg" },
  { code: "denmark", flag: "/icons/flag/flag-150.svg" },
  { code: "democratic-republic-of-the-congo", flag: "/icons/flag/flag-151.svg" },
  { code: "czechia", flag: "/icons/flag/flag-152.svg" },
  { code: "cyprus", flag: "/icons/flag/flag-153.svg" },
  { code: "curacao", flag: "/icons/flag/flag-154.svg" },
  { code: "cuba", flag: "/icons/flag/flag-155.svg" },
  { code: "croatia", flag: "/icons/flag/flag-156.svg" },
  { code: "costa-rica", flag: "/icons/flag/flag-157.svg" },
  { code: "republic-of-the-congo", flag: "/icons/flag/flag-158.svg" },
  { code: "comoros", flag: "/icons/flag/flag-159.svg" },
  { code: "colombia", flag: "/icons/flag/flag-160.svg" },
  { code: "china", flag: "/icons/flag/flag-161.svg" },
  { code: "chile", flag: "/icons/flag/flag-162.svg" },
  { code: "chad", flag: "/icons/flag/flag-163.svg" },
  { code: "central-african-republic", flag: "/icons/flag/flag-164.svg" },
  { code: "cape-verde", flag: "/icons/flag/flag-165.svg" },
  { code: "canada", flag: "/icons/flag/flag-166.svg" },
  { code: "cameroon", flag: "/icons/flag/flag-167.svg" },
  { code: "cambodia", flag: "/icons/flag/flag-168.svg" },
  { code: "burundi", flag: "/icons/flag/flag-169.svg" },
  { code: "burkina-faso", flag: "/icons/flag/flag-170.svg" },
  { code: "bulgaria", flag: "/icons/flag/flag-171.svg" },
  { code: "brunei", flag: "/icons/flag/flag-172.svg" },
  { code: "brazil", flag: "/icons/flag/flag-173.svg" },
  { code: "bouvet-island", flag: "/icons/flag/flag-174.svg" },
  { code: "botswana", flag: "/icons/flag/flag-175.svg" },
  { code: "bosnia-and-herzegovina", flag: "/icons/flag/flag-176.svg" },
  { code: "bolivia", flag: "/icons/flag/flag-177.svg" },
  { code: "bhutan", flag: "/icons/flag/flag-178.svg" },
  { code: "benin", flag: "/icons/flag/flag-179.svg" },
  { code: "belize", flag: "/icons/flag/flag-180.svg" },
  { code: "belgium", flag: "/icons/flag/flag-181.svg" },
  { code: "belarus", flag: "/icons/flag/flag-182.svg" },
  { code: "barbados", flag: "/icons/flag/flag-183.svg" },
  { code: "bangladesh", flag: "/icons/flag/flag-184.svg" },
  { code: "bahrain", flag: "/icons/flag/flag-185.svg" },
  { code: "bahamas", flag: "/icons/flag/flag-186.svg" },
  { code: "azerbaijan", flag: "/icons/flag/flag-187.svg" },
  { code: "austria", flag: "/icons/flag/flag-188.svg" },
  { code: "aruba", flag: "/icons/flag/flag-189.svg" },
  { code: "armenia", flag: "/icons/flag/flag-190.svg" },
  { code: "argentina", flag: "/icons/flag/flag-191.svg" },
  { code: "australia", flag: "/icons/flag/flag-192.svg" },
  { code: "antigua-and-barbuda", flag: "/icons/flag/flag-193.svg" },
  { code: "angola", flag: "/icons/flag/flag-194.svg" },
  { code: "andorra", flag: "/icons/flag/flag-195.svg" },
  { code: "algeria", flag: "/icons/flag/flag-196.svg" },
  { code: "albania", flag: "/icons/flag/flag-197.svg" },
  { code: "afghanistan", flag: "/icons/flag/flag-198.svg" },
]
