#!/usr/bin/env bash
set -euo pipefail
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd -- "$script_dir/../.." && pwd)"
workflow="$repo_root/.github/workflows/notify-app-main.yml"
test -f "$workflow"
grep -Fq 'branches: ["main"]' "$workflow"
grep -Fq 'timeout-minutes: 20' "$workflow"
grep -Fq 'CI_GITHUB_TOKEN' "$workflow"
grep -Fq 'fine-grained PAT with Contents read/write on rktclgh/ieum_BE' "$workflow"
grep -Fq 'event_type: "frontend-updated"' "$workflow"
grep -Fq '"fe_sha": "${{ github.sha }}"' "$workflow"
grep -Fq 'cancel-in-progress: true' "$workflow"
grep -Fq 'git fetch origin main --depth=1' "$workflow"
grep -Fq 'git rev-parse origin/main' "$workflow"
grep -Fq 'vars.NEXT_PUBLIC_GOOGLE_CLIENT_ID' "$workflow"
grep -Fq 'vars.NEXT_PUBLIC_KAKAO_REST_API_KEY' "$workflow"
grep -Fq 'test -s out/index.html' "$workflow"
grep -Fq 'test -s out/index.txt' "$workflow"
grep -Fq 'test -s out/404.html' "$workflow"
! grep -Fq 'continue-on-error: true' "$workflow"
